module.exports = {
  preset: 'react-native',
  moduleNameMapper: {
    '\\.(css)$': '<rootDir>/__mocks__/styleMock.js',
    '^@react-navigation/native$': '<rootDir>/__mocks__/reactNavigationNative.js',
    '^@react-navigation/native-stack$': '<rootDir>/__mocks__/reactNavigationNativeStack.js',
    '^@react-native-async-storage/async-storage$': '<rootDir>/__mocks__/asyncStorage.js',
    '^@react-native-clipboard/clipboard$': '<rootDir>/__mocks__/clipboard.js',
    '^@react-native-firebase/app$': '<rootDir>/__mocks__/rnFirebaseApp.js',
    '^@react-native-firebase/functions$': '<rootDir>/__mocks__/rnFirebaseFunctions.js',
    '^@react-native-firebase/analytics$': '<rootDir>/__mocks__/rnFirebaseAnalytics.js',
    '^@react-native-firebase/auth$': '<rootDir>/__mocks__/rnFirebaseAuthModular.js',
    '^@react-native-firebase/auth/lib/modular$': '<rootDir>/__mocks__/rnFirebaseAuthModular.js',
    '^@react-native-firebase/firestore/lib/modular$': '<rootDir>/__mocks__/rnFirebaseFirestoreModular.js',
    '^react-native-fbsdk-next$': '<rootDir>/__mocks__/reactNativeFbsdkNext.js',
    '^react-native-tracking-transparency$': '<rootDir>/__mocks__/reactNativeTrackingTransparency.js',
    '^react-native-google-mobile-ads$': '<rootDir>/__mocks__/reactNativeGoogleMobileAds.js',
    '^react-native-calendars$': '<rootDir>/__mocks__/reactNativeCalendars.js',
    '^react-native-purchases$': '<rootDir>/__mocks__/reactNativePurchases.js',
    '^react-native-purchases-ui$': '<rootDir>/__mocks__/reactNativePurchasesUI.js',
    '^@notifee/react-native$': '<rootDir>/__mocks__/notifeeReactNative.js',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|@react-navigation|@react-native-community|@react-native-firebase)/)',
  ],
};
